version: "3"

services:
  website:
    container_name: ${DOCKER_PROJECT}
    restart: always
    image: ${DOCKER_TAG}

    networks:
      frontend:

    logging:
      options:
        max-size: "10m"
        max-file: "5"

    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.rule=Host(`david.bertet.fr`) && PathPrefix(`/new`)
      - traefik.http.routers.portfolio.entrypoints=websecure
      - traefik.http.services.portfolio.loadbalancer.server.port=8080

networks:
  frontend:
    external: true
