version: "3"

services:
  website:
    container_name: ${DOCKER_PROJECT}
    restart: always
    image: ${DOCKER_TAG}

    network_mode: "bridge"
    expose:
      - "8080"

    logging:
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - VIRTUAL_HOST=david.bertet.fr
      - VIRTUAL_PORT=8080
